server: 
  port: 8761
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client: 
      serviceUrl:
       defaultZone: http://localhost:8761/eureka/
      
      logging:
       level:
       com.example.howtodoinjava: DEBUG
     
      netflix:
       eureka: OFF
       discovery: OFF
      
      
      spring:
          datasource:
            url: jdbc:mysql://134.209.152.67:3306/atas_product?useSSL=false
            username: remoteuser
            password: SomePASSWORD
      